# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.srcs/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/top_bd_axi_smc_0.xci
# IP: The module: 'top_bd_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/bd_c78a.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_0/bd_c78a_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_1/bd_c78a_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_2/bd_c78a_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_3/bd_c78a_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_4/bd_c78a_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_5/bd_c78a_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_6/bd_c78a_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_7/bd_c78a_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_8/bd_c78a_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_9/bd_c78a_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_10/bd_c78a_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_11/bd_c78a_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_12/bd_c78a_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_1/bd_c78a_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_1/bd_c78a_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_5/bd_c78a_s00a2s_0_ooc.xdc

# XDC: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_6/bd_c78a_sarn_0_ooc.xdc

# XDC: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_7/bd_c78a_srn_0_ooc.xdc

# XDC: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_8/bd_c78a_sawn_0_ooc.xdc

# XDC: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_9/bd_c78a_swn_0_ooc.xdc

# XDC: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_10/bd_c78a_sbn_0_ooc.xdc

# XDC: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_11/bd_c78a_m00s2a_0_ooc.xdc

# XDC: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_bd_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.srcs/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/top_bd_axi_smc_0.xci
# IP: The module: 'top_bd_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/bd_c78a.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_0/bd_c78a_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_1/bd_c78a_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_2/bd_c78a_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_3/bd_c78a_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_4/bd_c78a_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_5/bd_c78a_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_6/bd_c78a_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_7/bd_c78a_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_8/bd_c78a_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_9/bd_c78a_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_10/bd_c78a_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_11/bd_c78a_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_12/bd_c78a_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_1/bd_c78a_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_1/bd_c78a_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_5/bd_c78a_s00a2s_0_ooc.xdc

# XDC: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_6/bd_c78a_sarn_0_ooc.xdc

# XDC: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_7/bd_c78a_srn_0_ooc.xdc

# XDC: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_8/bd_c78a_sawn_0_ooc.xdc

# XDC: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_9/bd_c78a_swn_0_ooc.xdc

# XDC: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_10/bd_c78a_sbn_0_ooc.xdc

# XDC: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/bd_0/ip/ip_11/bd_c78a_m00s2a_0_ooc.xdc

# XDC: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/ip/top_bd_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_bd_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
