# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/top_bd/top_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_bd || ORIG_REF_NAME==top_bd} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_zynq_ultra_ps_e_0_0/top_bd_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_bd_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==top_bd_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_top_0_0/top_bd_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_bd_top_0_0 || ORIG_REF_NAME==top_bd_top_0_0} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_ps8_0_axi_periph_0/top_bd_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_bd_ps8_0_axi_periph_0 || ORIG_REF_NAME==top_bd_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_rst_ps8_0_99M_0/top_bd_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_bd_rst_ps8_0_99M_0 || ORIG_REF_NAME==top_bd_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_axi_smc_0/top_bd_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_bd_axi_smc_0 || ORIG_REF_NAME==top_bd_axi_smc_0} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_ila_0_0/top_bd_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_bd_ila_0_0 || ORIG_REF_NAME==top_bd_ila_0_0} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_auto_pc_0/top_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_bd_auto_pc_0 || ORIG_REF_NAME==top_bd_auto_pc_0} -quiet] -quiet

# XDC: /users/yyang22/thesis/aegnn_project/vivado_dir/sys_acc/sys_acc.gen/sources_1/bd/top_bd/top_bd_ooc.xdc
